apiVersion: v1
kind: Service
metadata:
  name: my-node-app-preview-service
  namespace: default
spec:
  selector:
    app: my-node-app
    color: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
