name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    # - name: Run Tests (Optional but Good Practice)
    #   run: npm test

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
  
  deploy-ec2:
      runs-on: ubuntu-latest
      needs: build-and-push

      steps:
        - name: Deploy to deploy ec2
          uses: appleboy/ssh-action@v1.0.2
          with: 
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            password: ${{ secrets.EC2_SSH_KEY }}
            script: 
              cd /home/ubuntu/my-node-devops-app

              docker compose down
              docker compose pull
              docker compose up -d --build